### ISSUE TITLE
[L06] Potential function clashes

### ISSUE THREAD

**Issue by cylon56** [compound-finance/comet#391]
The [`TransparentUpgradeableConfiguratorProxy`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/TransparentUpgradeableConfiguratorProxy.sol) overrides the [`_beforeCallback`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/TransparentUpgradeableConfiguratorProxy.sol#L20) function. 

Concretely, the `_beforeCallback` function is implemented in the [`TransparentUpgradeableProxy`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/vendor/proxy/transparent/TransparentUpgradeableProxy.sol#L121) contract to avoid the `admin` of the contract to call the implementation logic directly.

This feature is removed in `TransparentUpgradeableConfiguratorProxy` contract, where the `admin` is allowed now to call directly the implementation by triggering the fallback function as a normal user would do. This is needed because of the [`deployAndUpgrade`](https://github.com/compound-finance/comet/blob/0f1221967149115f50a09681eea9580879ee7720/contracts/CometProxyAdmin.sol#L16) function of the `CometProxyAdmin` which sees the `admin` calling the `Configurator.deploy` function. 

This is not a security issue on its own but it opens the door for potential clashes to happen. If one function is added either on the proxy or the logic contract, this can clash with any of the other contract functions. At this point, the admin will stop to be able to call the implementation contract (users will still be directed toward the implementation because of the `ifAdmin` modifier).

[This](https://medium.com/nomic-foundation-blog/malicious-backdoors-in-ethereum-proxies-62629adf3357) article specifies how crafting clashes may not be too hard of a computational task. [This](https://forum.openzeppelin.com/t/beware-of-the-proxy-learn-how-to-exploit-function-clashing/1070) article showcases how a new function in the proxy might actually enable clashes.

To avoid any unwanted behaviors, consider ensuring that the upgrade mechanism for `Configurator` always checks for potential clashes between the logic implementation and the proxy, especially if new functions are added.

**Comment by jflatow** [comment]
We analyzed the cases where a clash can occur and found that these cases are non-critical and recoverable.

The two types of clashes that can happen are:
 - New function on proxy is introduced that clashes with an existing function in the Configurator. Admin is no longer able to call the function on the Configurator.
   - To recover: The admin should still be able to upgrade the implementation of the proxy because that function lives on the proxy. Governance can simply introduce a new version of Configurator without the clash and upgrade the proxy to this new implementation.
 - New function on Configurator is introduced that clashes with an existing function on the proxy. Admin cannot call this new Configurator function.	
   - To recover: Same recovery path as above. Function clashes only prevent the admin from calling a function on the Configurator, so the admin is still able to call the upgrade function on the proxy itself.

In either case, the contracts are in a recoverable state and nothing malicious can happen unless the admin is malicious.

We are also exploring a slither-check-upgradeability plugin of slither library to check for clashes of functions between ConfiguratorProxy and Configurator (#430).

**Comment by jflatow** [comment]
We added the slither check in addition to the above guidance/remedies, closing.
